version: "3.8"

services:
  backend:
    container_name: backend_api
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: interview123
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db-vol:/var/lib/mysql

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    external: false

volumes:
  db-vol:
